
spring:
  application:
    name: auth
  config:
    import: configserver:http://localhost:8888
  data:
    mongodb:
      database: vms-user-db

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org:
      springframework:
        security: Trace

